server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
      item-service: /item/** # 将商品微服务映射到/item/**
      user-service: /user/**  # 将用户微服务映射到/user/**
      auth-service: /auth/**  # 将授权微服务映射到/auth/**
      search-service: /search/**  # 将搜索微服务映射到/search/**
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
           timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
   pubKeyPath: W:/data/rsa/rsa.pub
   cookieName: LY_TOKEN
  filter:                  #配置白名单路径
    allowPaths:     # - 开头表示是数组
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
    #  - /api/item